workflows:
  flutter-game-release:
    name: Flutter Game APK Release
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.fluttergame"
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - erikcrayfish@gmail.com
